// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8006)
// Generated by LuaStick, Nov  3 2025.

#pragma once

// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8014)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8014)
#include "main.h"

// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8022)
struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
