// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(7997)
// Generated by LuaStick, Oct 27 2025.

#pragma once

// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8005)
#include "..\..\LuaStick\files\Sticklib.h"
// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8005)
#include "main.h"

// Generated at "C:\src\lua\luastick\LuaStick\src\LuaStick.cpp"(8013)
struct lua_State;
extern void luastick_init(lua_State* L);


#include "..\..\LuaStick\files\Stickrun.h"
